### ISSUE TITLE
Not all Endpoints are found

### ISSUE THREAD

**Issue by xetra11** [miguelcordovam/intellij_plugins#2]
It occurs that some mapping are not found by the exension! I cannot give you a reproducable state unfortunalely

**Comment by miguelcordovam** [comment]
Hi, could you please provide an example? The plugin does not work if you are using inheritance in your controllers. The class needs to be annotated, otherwise it won't find it.

**Comment by xetra11** [comment]
fixed with 1.4 Update. Thanks!
